name = input("Enter your name:")
roll_no = input("Enter your roll number:")
dept = input("Enter yur Branch:")

print("Enter your marks:")
C = int(input("C :"))
C1 = int(input("C++ :"))
python = int(input("Python :"))
java = int(input("Java :"))
AI = int(input("AI :"))

print("="*10,"Report Card","="*10)
print("Name : ",name)
print("Roll.no: ",roll_no)
print("Department: ",dept)
print("="*10,"Marks Secured","="*10)
print("C Programming:",C)
print("C++ :",C1)
print("Python :",python)
print("Java:",java)
print("AI:",AI)
print("="*20)
print("Total marks :",C+C1+python+java+AI)
print("="*20)
